name: Changelog

on:
  pull_request:
    types:
      - labeled
      - opened
      - unlabeled

jobs:
  assign-to-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/assign-changelog
        with:
            repo-token: ${{secrets.GITHUB_TOKEN}}